### ISSUE TITLE
Error in PTP-enabled .cameraHWSync data file

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/trodes_to_nwb#66]
Came across a dataset with unexpected values for time recorded in the `.cameraHWSync` file. The first chunk of timestamps had much too small of values for time (~1e4 instead of the normal ~1e9). Partway through file there is large jump.  

Confirmed that ptp-enabled in the rec header, meaning that these values get put in directly to the spatial series.  

Is this a case we need to function for or purely an error at recording time?

**Potential Work-around**
There are trodes timestamps in the file. Could add an option to manually set ptp-disabled, and calculate position time based on this instead.

**Code to load error data file in dataframe**
```
from trodes_to_nwb.convert_position import read_trodes_datafile
import pandas as pd

position_timestamps_filepath = '/stelmo/sc4712/rats/SC1001/raw/20230905/20230905_SC1001_07_s4.1.videoTimeStamps.cameraHWSync'
video_timestamps = (
        pd.DataFrame(read_trodes_datafile(position_timestamps_filepath)["data"])
        .set_index("PosTimestamp")
        .rename(columns={"frameCount": "HWframeCount"})
)
```

**Comment by edeno** [comment]
This seems like PTP is not enabled based on the size of the timestamps. Then possibly it was enabled? Agree that an override would be fine. I guess another good thing to do is figure out a way to throw a warning or an error in these situations. The problem is that that probably involves comparing to the mcu timestamps or maybe just converting the first timestamp to an actual date and throwing a warning if it's before the year 2000 or something of the sort.
